name: API Tests

# Trigger on push to main, PRs, or manual dispatch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-postman:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up PHP & Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist

      # 3. Start Laravel in the background
      - name: Serve Laravel API
        run: php artisan serve --host=127.0.0.1 --port=8091 > /dev/null 2>&1 &

      # 4. Wait until the API responds
      - name: Wait for API to respond
        run: |
          for i in {1..15}; do
            if curl --silent --fail http://127.0.0.1:8091/api/users/register; then
              echo "API is up!"
              break
            fi
            echo "Waiting for API..."
            sleep 2
          done

      # 5. Install Node.js & Newman
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      # 6. Run Register Tests with two CSV files
      - name: Register Tests (AU-01)
        run: |
          newman run Register.postman_collection.json \
            -e HW07.postman_environment.json \
            --iteration-data AU-01.csv \
            --reporters cli,junit \
            --reporter-junit-export reports/register-AU-01.xml

      - name: Register Tests (AU-02-09)
        run: |
          newman run Register.postman_collection.json \
            -e HW07.postman_environment.json \
            --iteration-data AU-02-09.csv \
            --reporters cli,junit \
            --reporter-junit-export reports/register-AU-02-09.xml

      # 7. Run Login Tests
      - name: Login Tests (AU-10-13)
        run: |
          newman run Login.postman_collection.json \
            -e HW07.postman_environment.json \
            --iteration-data AU-10-13.csv \
            --reporters cli,junit \
            --reporter-junit-export reports/login-AU-10-13.xml

      # 8. Run Forgot-Password Tests
      - name: Forgot-Password Tests (AU-14-17)
        run: |
          newman run "Forget password.postman_collection.json" \
            -e HW07.postman_environment.json \
            --iteration-data AU-14-17.csv \
            --reporters cli,junit \
            --reporter-junit-export reports/forgot-AU-14-17.xml

      # 9. Upload JUnit XML reports as artifacts
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: reports/*.xml
