name: CI · Postman API Tests with Docker Compose & Composer on Host (SPRINT5)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout backend (practice-software-testing)
        uses: actions/checkout@v4
        with:
          repository: testsmith-io/practice-software-testing
          path: api

      - name: Switch to sprint5-with-bugs
        run: |
          sed -i 's/^SPRINT=.*/SPRINT=sprint5-with-bugs/' ./api/.env

      - name: Start Docker Compose
        working-directory: ./api
        run: docker compose up --build -d

      - name: Install Composer (host)
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      # CHÚ Ý: composer install ở đúng nơi chứa source!
      - name: Composer install on host
        working-directory: ./api/sprint5-with-bugs
        run: composer install --no-interaction --no-ansi --no-progress

      - name: Migrate & Seed Database
        working-directory: ./api
        run: |
          docker compose exec laravel-api php artisan migrate:fresh --seed

      - name: Wait for API ready
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          for i in {1..20}; do
            if curl -s http://localhost:8091/api/documentation > /dev/null; then
              echo "API is ready!";
              exit 0;
            fi
            echo "Waiting for API... ($i/20)"
            sleep 5
          done
          echo "API did not start in time" && exit 1

      - name: Install Postman CLI
        run: |
          curl -sL https://dl-cli.pstmn.io/install/linux64.sh | bash

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Register tests
        run: |
          postman collection run \
            ./Register.postman_collection.json \
            -e ./HW07.postman_environment.json \
            --iteration-data ./register-data.csv \
            --reporters cli,junit \
            --reporter-junit-export reports/register-results.xml

      - name: Run Login tests
        run: |
          postman collection run \
            ./Login.postman_collection.json \
            -e ./HW07.postman_environment.json \
            --iteration-data ./login-data.csv \
            --reporters cli,junit \
            --reporter-junit-export reports/login-results.xml

      - name: Run Forgot Password tests
        run: |
          postman collection run \
            "./Forget password.postman_collection.json" \
            -e ./HW07.postman_environment.json \
            --iteration-data ./forgot-password-data.csv \
            --reporters cli,junit \
            --reporter-junit-export reports/forgot-password-results.xml

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-junit-reports
          path: reports/*.xml

      - name: Shutdown Docker Compose
        if: always()
        working-directory: ./api
        run: docker compose down
